create table tb_payment_method (id int8 generated by default as identity, description varchar(255), primary key (id));
create table tb_sale (id int8 generated by default as identity, date date, total float8, volume int4, payment_method_id int8, store_id int8, primary key (id));
create table tb_store (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sale add constraint FKr1t2k051avij8fc6ixi36exyw foreign key (payment_method_id) references tb_payment_method;
alter table if exists tb_sale add constraint FKb42e4bb6i9ujys2n4ytb97kj2 foreign key (store_id) references tb_store;
